In [79]:
import pandas as pd

In [80]:
data1 = pd.read_csv('crime_data1.csv')
data2 = pd.read_csv('covid_data.csv')

output_df = pd.merge(data1, data2, how='left')

print(output)

       offense_id    rpt_date  occur_date occur_time           UC2_Literal  \
0        21320347    2/1/2021   1/31/2021      00:00  LARCENY-FROM VEHICLE
1       203661993    1/1/2021   1/31/2020      20:30  LARCENY-FROM VEHICLE
2       203662299    1/5/2021  12/31/2020      23:36  LARCENY-FROM VEHICLE
3       210010977   1/25/2021    1/1/2021      03:00            AUTO THEFT
4       210011211    1/1/2021    1/1/2021      05:43  LARCENY-FROM VEHICLE
...           ...         ...         ...        ...                   ...
15850   202920087  10/18/2020  10/18/2020       0:10               ROBBERY
15851   202810281   10/7/2020   10/7/2020       1:30               ROBBERY
15852   202770463   10/3/2020   10/3/2020       2:10            AUTO THEFT
15853   202671810   9/23/2020   9/23/2020      22:00           AGG ASSAULT
15854   203161000  11/11/2020   11/4/2020       0:00   LARCENY-NON VEHICLE

              neighborhood npu        lat       long    use_date    zip  \
0                 Downtown   M  33.760759 -84.383773  2021-02-01  30303
1                 Downtown   M  33.757453 -84.392698  2021-01-01  30303
2                 Downtown   M  33.750347 -84.389580  2021-01-05  30303
3                 Downtown   M  33.757774 -84.394966  2021-01-25  30303
4                 Downtown   M  33.757774 -84.394966  2021-01-01  30303
...                    ...  ..        ...        ...         ...    ...
15850  South River Gardens   Z  33.650292 -84.366814  2020-10-18  30297
15851  South River Gardens   Z  33.650292 -84.366814  2020-10-07  30297
15852  South River Gardens   Z  33.650292 -84.366814  2020-10-03  30297
15853             Downtown   M  33.749080 -84.388240  2020-09-23  30334
15854        Lincoln Homes   G  33.803547 -84.480752  2020-11-11  30369

        county  total_cases  deaths
0       Fulton        279.0     1.0
1       Fulton        981.0     0.0
2       Fulton        728.0     2.0
3       Fulton        460.0     5.0
4       Fulton        981.0     0.0
...        ...          ...     ...
15850  Clayton         24.0     1.0
15851  Clayton         48.0     1.0
15852  Clayton         32.0     0.0
15853   Fulton        146.0     3.0
15854   Fulton        194.0     2.0

[15855 rows x 14 columns]

In [95]:
clean_df = output_df.dropna(how='any', inplace=False)
clean_df.drop(['rpt_date', 'occur_time'], inplace=True, axis=1)
crime_covid_df = pd.DataFrame(clean_df)
crime_covid_df.head(-1)

/Users/shangjungtsang/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,offense_id,occur_date,UC2_Literal,neighborhood,npu,lat,long,use_date,zip,county,total_cases,deaths
0,21320347,1/31/2021,LARCENY-FROM VEHICLE,Downtown,M,33.760759,-84.383773,2021-02-01,30303,Fulton,279.0,1.0
1,203661993,1/31/2020,LARCENY-FROM VEHICLE,Downtown,M,33.757453,-84.392698,2021-01-01,30303,Fulton,981.0,0.0
2,203662299,12/31/2020,LARCENY-FROM VEHICLE,Downtown,M,33.750347,-84.389580,2021-01-05,30303,Fulton,728.0,2.0
3,210010977,1/1/2021,AUTO THEFT,Downtown,M,33.757774,-84.394966,2021-01-25,30303,Fulton,460.0,5.0
4,210011211,1/1/2021,LARCENY-FROM VEHICLE,Downtown,M,33.757774,-84.394966,2021-01-01,30303,Fulton,981.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
15849,203330711,11/28/2020,LARCENY-NON VEHICLE,South River Gardens,Z,33.648495,-84.367875,2020-11-28,30297,Clayton,51.0,0.0
15850,202920087,10/18/2020,ROBBERY,South River Gardens,Z,33.650292,-84.366814,2020-10-18,30297,Clayton,24.0,1.0
15851,202810281,10/7/2020,ROBBERY,South River Gardens,Z,33.650292,-84.366814,2020-10-07,30297,Clayton,48.0,1.0
15852,202770463,10/3/2020,AUTO THEFT,South River Gardens,Z,33.650292,-84.366814,2020-10-03,30297,Clayton,32.0,0.0
15853,202671810,9/23/2020,AGG ASSAULT,Downtown,M,33.749080,-84.388240,2020-09-23,30334,Fulton,146.0,3.0

In [96]:
clean_df.to_csv("crime_covid2.csv", index=False, header=True)